public with sharing class MetadataSubscriberPackageDependencies {
    public List<Map<String,String>> ids = new List<Map<String,String>>();


        //public Map<String,String> dependencies; //TODO:FIX.....    

    /* Example Dependencies JSON
        {
        "Dependencies": {
            "ids": [
            {
                "subscriberPackageVersionId": "04t1K000002J0KKQA0"
            },
            {
                "subscriberPackageVersionId": "04t1t0000034vZjAAI"
            }
            ]
        }
        }
    */
}
